# Generated by Django 4.2 on 2023-05-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='-', max_length=40, verbose_name='Adres')),
                ('tel', models.CharField(default='-', max_length=10, verbose_name='Telefon numarası')),
                ('job', models.CharField(blank=True, default='-', max_length=20, verbose_name='Meslek')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile', verbose_name='Profil Resmi')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
        ),
    ]
