# Generated by Django 4.2 on 2023-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_now',
            field=models.DateField(auto_now_add=True, verbose_name='Tarih - Saat'),
        ),
    ]
