# Generated by Django 4.2 on 2023-05-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_dramatype_gametype_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramatype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='gametype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori'),
        ),
    ]
